#!/usr/bin/env python3
"""Compile point/triangle module-reuse and PointSize read/mixed-store fixtures."""
from pathlib import Path
import struct
import subprocess
import tempfile
here = Path(__file__).resolve().parent
with tempfile.TemporaryDirectory(prefix='hybris-point-size-') as tmp:
    output = []
    for name, stage, defines in [('Vertex', 'vert', []), ('Read', 'vert', ['-DPOINT_READ=1']),
                                  ('Mixed', 'vert', ['-DPOINT_MIXED=1']), ('Fragment', 'frag', [])]:
        path = Path(tmp) / (name + '.spv')
        subprocess.run(['glslangValidator', '-V', *defines, str(here / ('point-size.' + stage)), '-o', str(path)], check=True)
        subprocess.run(['spirv-val', '--target-env', 'vulkan1.0', str(path)], check=True)
        data = path.read_bytes()
        words = struct.unpack('<' + 'I' * (len(data) // 4), data)
        rows = ['    ' + ', '.join(f'0x{w:08x}' for w in words[i:i+8]) + ',' for i in range(0, len(words), 8)]
        output.append('static const uint32_t kPoint' + name + '[] = {\n' + '\n'.join(rows) + '\n};\n')
    (here / 'point-size.inc').write_text('// Generated by generate-point-size.py.\n' + '\n'.join(output))
