#!/usr/bin/env python3
"""Compile VS/FS fixtures for vertex/fragment Location width matching."""
from pathlib import Path
import struct
import subprocess
import tempfile
here = Path(__file__).resolve().parent
with tempfile.TemporaryDirectory(prefix='hybris-inout-') as tmp:
    output = []
    for name, source in [('Vertex', 'inout.vert'), ('Narrow', 'inout.frag'),
                         ('Match', 'inout-match.frag'), ('Scalar', 'inout-scalar.frag')]:
        path = Path(tmp) / (name + '.spv')
        stage = 'vert' if source.endswith('.vert') else 'frag'
        subprocess.run(['glslangValidator', '-V', '-S', stage, str(here / source), '-o', str(path)], check=True)
        subprocess.run(['spirv-val', '--target-env', 'vulkan1.0', str(path)], check=True)
        data = path.read_bytes()
        words = struct.unpack('<' + 'I' * (len(data) // 4), data)
        rows = ['    ' + ', '.join(f'0x{w:08x}' for w in words[i:i + 8]) + ',' for i in range(0, len(words), 8)]
        output.append('static const uint32_t kInout' + name + '[] = {\n' + '\n'.join(rows) + '\n};\n')
    (here / 'inout.inc').write_text('// Generated by generate-inout.py.\n' + '\n'.join(output))
