#!/usr/bin/env python3
"""Regenerate the scaled probe's single and multi-entry shader assets."""
from pathlib import Path
import re
import struct
import subprocess
import tempfile
from group_decorations import group_module

here = Path(__file__).resolve().parent
with tempfile.TemporaryDirectory(prefix='hybris-scaled-shaders-') as temporary:
    output = Path(temporary)
    def compile_shader(stage, name, extra=()):
        target = output / (name + '.spv')
        subprocess.run(['glslangValidator', '-V', *extra, str(here / ('scaled.' + stage)), '-o', str(target)], check=True)
        return target
    vertex = compile_shader('vert', 'vertex')
    fragment = compile_shader('frag', 'fragment')
    selected = compile_shader('vert', 'selected', ('-DHYBRIS_SCALED_MULTI=1', '--source-entrypoint', 'main', '-e', 'scaled_vertex'))
    alternate = compile_shader('vert', 'alternate', ('-DHYBRIS_SCALED_MULTI=1', '-DHYBRIS_SCALED_ALTERNATE=1', '--source-entrypoint', 'main', '-e', 'alternate_vertex'))
    literal = compile_shader('vert', 'literal', ('-DHYBRIS_SCALED_LITERALS=1',))
    assembly = subprocess.check_output(['spirv-dis', '--raw-id', str(literal)], text=True)
    inputs = set(re.findall(r'^\s*(%\d+) = OpVariable %\d+ Input$', assembly, re.M))
    locations = set(re.findall(r'OpDecorate (%\d+) Location 0$', assembly, re.M))
    target, = inputs & locations
    target_id = int(target[1:])
    # SPIRV-Tools disassembly distinguishes IDs from literal operands. Swap
    # only ID tokens so the input has ID 3 while shuffle component 3 stays 3.
    assembly = re.sub(r'%(\d+)\b', lambda m: '%' + str(3 if int(m[1]) == target_id else target_id if int(m[1]) == 3 else int(m[1])), assembly)
    assembly_path = output / 'literal.spvasm'
    assembly_path.write_text(assembly)
    subprocess.run(['spirv-as', '--target-env', 'spv1.0', '--preserve-numeric-ids', str(assembly_path), '-o', str(literal)], check=True)
    multiple = output / 'multiple.spv'
    subprocess.run(['spirv-link', '--target-env', 'vulkan1.1', str(alternate), str(fragment), str(selected), '-o', str(multiple)], check=True)
    aggregates = []
    for variant, name in enumerate(('matrix', 'array', 'nested', 'matarray'), 3):
        target = output / (name + '.spv')
        subprocess.run(['glslangValidator', '-V', '-DHYBRIS_AGGREGATE=' + str(variant),
                        str(here / 'scaled.aggregate.vert'), '-o', str(target)], check=True)
        aggregates.append((target, 'scaled.' + name + '.inc', 'kScaled' + name.title() + 'Spv'))
    divisor = output / 'divisor.spv'
    subprocess.run(['glslangValidator', '-V', str(here / 'scaled.divisor.vert'), '-o', str(divisor)], check=True)
    aggregates.append((divisor, 'scaled.divisor.inc', 'kScaledDivisorSpv'))
    specialized = output / 'specialized.spv'
    subprocess.run(['glslangValidator', '-V', str(here / 'scaled.spec.vert'), '-o', str(specialized)], check=True)
    aggregates.append((specialized, 'scaled.spec.inc', 'kScaledSpecSpv'))
    direct = output / 'specialized-direct.spv'
    subprocess.run(['glslangValidator', '-V', '-DHYBRIS_SPEC_DIRECT=1', str(here / 'scaled.spec.vert'), '-o', str(direct)], check=True)
    aggregates.append((direct, 'scaled.spec-direct.inc', 'kScaledSpecDirectSpv'))
    for original, name, symbol in ((vertex, 'group', 'kScaledGroupSpv'),
                                    (multiple, 'group-multi', 'kScaledGroupMultiSpv'),
                                    (specialized, 'group-spec', 'kScaledGroupSpecSpv')):
        target = output / (name + '.spv')
        target.write_bytes(group_module(original.read_bytes()))
        aggregates.append((target, 'scaled.' + name + '.inc', symbol))
    for path, filename, symbol in ((vertex, 'scaled.vert.inc', 'kScaledVertSpv'),
                                   (fragment, 'scaled.frag.inc', 'kScaledFragSpv'),
                                   (multiple, 'scaled.multi.inc', 'kScaledMultiSpv'),
                                   (literal, 'scaled.literal.inc', 'kScaledLiteralSpv'), *aggregates):
        subprocess.run(['spirv-val', '--target-env', 'vulkan1.1', str(path)], check=True)
        binary = path.read_bytes()
        words = struct.unpack('<' + 'I' * (len(binary) // 4), binary)
        rows = ''.join('  ' + ', '.join(f'0x{word:08x}' for word in words[i:i+8]) + ',\n' for i in range(0, len(words), 8))
        (here / filename).write_text('// Generated by shaders/generate-scaled.py.\nstatic const uint32_t ' + symbol + '[] = {\n' + rows + '};\n')
