#!/usr/bin/env python3
"""Build packed SNORM fixtures with scalar and dynamically indexed vector inputs."""
from pathlib import Path
import struct
import subprocess
import tempfile
here = Path(__file__).resolve().parent
with tempfile.TemporaryDirectory(prefix='hybris-packed-') as tmp:
    output = []
    for width in range(1, 5):
        path = Path(tmp) / f'{width}.spv'
        subprocess.run(['glslangValidator', '-V', f'-DWIDTH={width}', str(here / 'packed.vert'), '-o', str(path)], check=True)
        subprocess.run(['spirv-val', '--target-env', 'vulkan1.0', str(path)], check=True)
        data = path.read_bytes()
        words = struct.unpack('<' + 'I' * (len(data) // 4), data)
        rows = ['    ' + ', '.join(f'0x{w:08x}' for w in words[i:i+8]) + ',' for i in range(0, len(words), 8)]
        output.append(f'static const uint32_t kPacked{width}[] = {{\n' + '\n'.join(rows) + '\n};\n')
    (here / 'packed.inc').write_text('// Generated by generate-packed.py.\n' + '\n'.join(output))
