#!/usr/bin/env python3
"""Compile a fragment fixture that selects a zero constant after ImageFetch."""
from pathlib import Path
import struct
import subprocess
import tempfile
here = Path(__file__).resolve().parent
with tempfile.TemporaryDirectory(prefix='hybris-image-bounds-') as tmp:
    path = Path(tmp) / 'bounds.spv'
    subprocess.run(['spirv-as', '--target-env', 'spv1.0', str(here / 'image-bounds.spvasm'), '-o', str(path)], check=True)
    subprocess.run(['spirv-val', '--target-env', 'vulkan1.0', str(path)], check=True)
    data = path.read_bytes()
    words = struct.unpack('<' + 'I' * (len(data) // 4), data)
    rows = ['    ' + ', '.join(f'0x{w:08x}' for w in words[i:i + 8]) + ',' for i in range(0, len(words), 8)]
    (here / 'image-bounds.inc').write_text(
        '// Generated by generate-image-bounds.py.\n'
        'static const uint32_t kImageBounds[] = {\n' + '\n'.join(rows) + '\n};\n')
