#!/usr/bin/env python3
"""Reorder the existing rendering fixture's builtin block to exercise pruning.

The block becomes ClipDistance, CullDistance, Position, PointSize. SPIRV-Tools
validates it independently. Fresh access indices preserve all other uses of the
original constants; rendering expectations are identical to scaled.vert.
"""
from pathlib import Path
import re
import struct
import subprocess
import tempfile

here = Path(__file__).resolve().parent
with tempfile.TemporaryDirectory(prefix='hybris-builtin-fixture-') as tmp:
    tmp = Path(tmp)
    binary = tmp / 'vertex.spv'
    subprocess.run(['glslangValidator', '-V', str(here / 'scaled.vert'), '-o', str(binary)], check=True)
    assembly = subprocess.check_output(['spirv-dis', str(binary)], text=True)
    members = re.findall(r'OpMemberDecorate %gl_PerVertex (\d+) BuiltIn (\w+)', assembly)
    assert members == [('0', 'Position'), ('1', 'PointSize'), ('2', 'ClipDistance'), ('3', 'CullDistance')]
    old = re.search(r'(%gl_PerVertex = OpTypeStruct) (.+)', assembly)
    types = old[2].split()
    assert len(types) == 4
    assembly = assembly.replace(old[0], old[1] + ' ' + ' '.join(types[i] for i in [2, 3, 0, 1]))
    remap = {0: 2, 1: 3, 2: 0, 3: 1}
    assembly = re.sub(r'(OpMember(?:Name|Decorate) %gl_PerVertex) (\d+)',
                      lambda m: m[1] + ' ' + str(remap[int(m[2])]), assembly)
    pointer = re.search(r'(%\w+) = OpTypePointer Output %gl_PerVertex', assembly)[1]
    variable = re.search(r'(%\w+) = OpVariable ' + re.escape(pointer) + r' Output', assembly)[1]
    constants = {m[1]: (m[2], int(m[3])) for m in re.finditer(r'(%\w+) = OpConstant (%\w+) (\d+)\s*$', assembly, re.M)}
    additions = []
    def rewrite(match):
        kind, old_index = constants[match[2]]
        name = '%hybris_member_' + str(len(additions))
        additions.append(name + ' = OpConstant ' + kind + ' ' + str(remap[old_index]))
        return match[1] + name
    assembly = re.sub(r'(Op(?:InBounds)?AccessChain %\w+ ' + re.escape(variable) + r' )(%\w+)', rewrite, assembly)
    assert additions
    assembly = re.sub(r'^(\s*%\w+ = OpFunction )', '\n'.join(additions) + r'\n\1', assembly, count=1, flags=re.M)
    source = tmp / 'reordered.spvasm'
    source.write_text(assembly)
    subprocess.run(['spirv-as', '--target-env', 'vulkan1.0', str(source), '-o', str(binary)], check=True)
    subprocess.run(['spirv-val', '--target-env', 'vulkan1.0', str(binary)], check=True)
    data = binary.read_bytes()
    words = struct.unpack('<' + 'I' * (len(data) // 4), data)
    rows = ['    ' + ', '.join(f'0x{w:08x}' for w in words[i:i + 8]) + ',' for i in range(0, len(words), 8)]
    (here / 'scaled.builtins.inc').write_text('// Generated by generate-unused-builtins.py.\n'
        'static const uint32_t kScaledBuiltinsSpv[] = {\n' + '\n'.join(rows) + '\n};\n')
