#!/usr/bin/env python3
"""Regenerate the scaled probe's single and multi-entry shader assets."""
from pathlib import Path
import struct
import subprocess
import tempfile

here = Path(__file__).resolve().parent
with tempfile.TemporaryDirectory(prefix='hybris-scaled-shaders-') as temporary:
    output = Path(temporary)
    def compile_shader(stage, name, extra=()):
        target = output / (name + '.spv')
        subprocess.run(['glslangValidator', '-V', *extra, str(here / ('scaled.' + stage)), '-o', str(target)], check=True)
        return target
    vertex = compile_shader('vert', 'vertex')
    fragment = compile_shader('frag', 'fragment')
    selected = compile_shader('vert', 'selected', ('-DHYBRIS_SCALED_MULTI=1', '--source-entrypoint', 'main', '-e', 'scaled_vertex'))
    alternate = compile_shader('vert', 'alternate', ('-DHYBRIS_SCALED_MULTI=1', '-DHYBRIS_SCALED_ALTERNATE=1', '--source-entrypoint', 'main', '-e', 'alternate_vertex'))
    multiple = output / 'multiple.spv'
    subprocess.run(['spirv-link', '--target-env', 'vulkan1.1', str(alternate), str(fragment), str(selected), '-o', str(multiple)], check=True)
    for path, filename, symbol in ((vertex, 'scaled.vert.inc', 'kScaledVertSpv'),
                                   (fragment, 'scaled.frag.inc', 'kScaledFragSpv'),
                                   (multiple, 'scaled.multi.inc', 'kScaledMultiSpv')):
        subprocess.run(['spirv-val', '--target-env', 'vulkan1.1', str(path)], check=True)
        binary = path.read_bytes()
        words = struct.unpack('<' + 'I' * (len(binary) // 4), binary)
        rows = ''.join('  ' + ', '.join(f'0x{word:08x}' for word in words[i:i+8]) + ',\n' for i in range(0, len(words), 8))
        (here / filename).write_text('// Generated by shaders/generate-scaled.py.\nstatic const uint32_t ' + symbol + '[] = {\n' + rows + '};\n')
