#!/usr/bin/env python3
"""Compile the BC image probe's application-side sampling shader."""
from pathlib import Path
import struct
import subprocess
import tempfile

here = Path(__file__).resolve().parent
with tempfile.TemporaryDirectory(prefix='hybris-bc-sample-') as directory:
    binary = Path(directory) / 'sample.spv'
    subprocess.run(['glslangValidator', '-V', str(here / 'bc-sample.comp'), '-o', str(binary)], check=True)
    subprocess.run(['spirv-val', '--target-env', 'vulkan1.1', str(binary)], check=True)
    data = binary.read_bytes()
    words = struct.unpack('<' + 'I' * (len(data) // 4), data)
    rows = ''.join('    ' + ', '.join(f'0x{word:08x}' for word in words[i:i+8]) + ',\n'
                   for i in range(0, len(words), 8))
    (here / 'bc-sample.inc').write_text('// Generated by generate-bc-sample.py.\n'
        'static const uint32_t bc_sample_spv[] = {\n' + rows + '};\n')
