#!/usr/bin/env python3
"""Regenerate and validate the four-descriptor widget shaders."""
from pathlib import Path
import struct
import subprocess
import tempfile

here = Path(__file__).resolve().parent
with tempfile.TemporaryDirectory() as tmp:
    for stage in ('vert', 'frag'):
        binary = Path(tmp) / (stage + '.spv')
        subprocess.run(['glslangValidator', '-V', '--target-env', 'vulkan1.0',
                        str(here / ('widget-multi.' + stage)), '-o', str(binary)], check=True)
        subprocess.run(['spirv-val', '--target-env', 'vulkan1.0', str(binary)], check=True)
        data = binary.read_bytes()
        words = struct.unpack('<' + 'I' * (len(data) // 4), data)
        name = 'kWidgetMulti' + stage.title() + 'Spv'
        lines = [', '.join('0x%08x' % word for word in words[i:i + 8]) for i in range(0, len(words), 8)]
        (here / ('widget-multi.' + stage + '.inc')).write_text(
            '// Generated by generate-widget-multi.py.\nstatic const uint32_t ' + name + '[] = {\n    ' +
            ',\n    '.join(lines) + '\n};\nstatic const size_t ' + name + '_word_count = sizeof(' + name + ') / 4;\n')
