#!/usr/bin/env python3
"""Generate BC6H half-bit references with the pinned official Mesa decoder.

This offline source is never linked into the probe or ICD. Temporary empty
Mesa includes are replaced by the adapter's minimal standard-C dependencies;
the selected fp16 routine does not call the float conversion declarations.
"""
import ctypes
import hashlib
import json
from pathlib import Path
import struct
import subprocess
import tempfile

here = Path(__file__).resolve().parent
source = here / 'texcompress_bptc_tmp.h'
metadata = json.loads((here / 'source.json').read_text())
assert hashlib.sha256(source.read_bytes()).hexdigest() == metadata['sha256']
# Hardware mode prefixes in the logical bcdec mode order. Two subset modes
# end their endpoint data at bit 77; the next five bits select the partition.
prefixes = [0, 1, 2, 6, 10, 14, 18, 22, 26, 30, 3, 7, 11, 15]
blocks = []
seed = 0xB6C06391
for config in range(64):
    for mode, prefix in enumerate(prefixes):
        value = 0
        for word in range(4):
            seed ^= (seed << 13) & 0xffffffff
            seed ^= seed >> 17
            seed ^= (seed << 5) & 0xffffffff
            value |= seed << (32 * word)
        bits = 2 if mode < 2 else 5
        value = (value & ~((1 << bits) - 1)) | prefix
        if mode < 10:
            value = (value & ~(31 << 77)) | ((config & 31) << 77)
        blocks.append(value.to_bytes(16, 'little'))
# Constant payloads add endpoint and index boundary cases in every valid mode.
for payload in [0, (1 << 128) - 1, int('55' * 16, 16), int('aa' * 16, 16)]:
    for mode, prefix in enumerate(prefixes):
        bits = 2 if mode < 2 else 5
        blocks.append(((payload & ~((1 << bits) - 1)) | prefix).to_bytes(16, 'little'))
outputs = []
with tempfile.TemporaryDirectory(prefix='hybris-bc6h-golden-') as directory:
    temp = Path(directory)
    (temp / 'util').mkdir()
    for name in ['bitscan.h', 'format_srgb.h', 'half_float.h', 'u_math.h']:
        (temp / 'util' / name).write_text('/* Offline adapter supplies required declarations. */\n')
    for optimization in ['-O1', '-O2']:
        library = temp / (optimization + '.so')
        subprocess.run(['cc', '-std=c11', optimization, '-shared', '-fPIC',
                        '-Werror=implicit-function-declaration', '-I', str(temp),
                        str(here / 'wrapper.c'), '-o', str(library)], check=True)
        decode = ctypes.CDLL(str(library)).decode
        decode.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_int]
        decode.restype = None
        variants = []
        for sign in [0, 1]:
            decoded = []
            for block in blocks:
                src = ctypes.create_string_buffer(block)
                dst = (ctypes.c_uint16 * 64)()
                decode(src, dst, sign)
                words = list(dst)
                assert all(words[i] == 0x3c00 for i in range(3, 64, 4))
                decoded.append(struct.pack('<64H', *words))
            variants.append(decoded)
        outputs.append(variants)
assert outputs[0] == outputs[1], 'Mesa optimization variants disagree'
golden = outputs[0]
lines = ['/* Generated by reference/bc6h/generate.py using pinned Mesa. */',
         '#define BC6H_VECTOR_COUNT %d' % len(blocks),
         'static const struct { uint32_t block[4], rgba[2][32]; } bc6h_vectors[BC6H_VECTOR_COUNT] = {']
for i, block in enumerate(blocks):
    pack = lambda data: ','.join('0x%08xu' % x for x in struct.unpack('<%dI' % (len(data)//4), data))
    lines.append('    {{%s}, {{%s}, {%s}}},' % (pack(block), pack(golden[0][i]), pack(golden[1][i])))
lines.append('};')
output = here.parent.parent / 'bc6h_fixture.inc'
output.write_text('\n'.join(lines) + '\n')
report = dict(blocks=len(blocks), modes=14, partitions_per_two_subset_mode=32,
              random_configurations_per_mode=64, fixed_payloads_per_mode=4,
              source=metadata, source_blocks_sha256=hashlib.sha256(b''.join(blocks)).hexdigest(),
              output_sha256=[hashlib.sha256(b''.join(v)).hexdigest() for v in golden],
              fixture_sha256=hashlib.sha256(output.read_bytes()).hexdigest(),
              generator_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
              adapter_sha256=hashlib.sha256((here/'wrapper.c').read_bytes()).hexdigest(),
              compiler=subprocess.check_output(['cc','--version'],text=True).splitlines()[0],
              optimization_variants=['-O1','-O2'], limitation='Not exhaustive endpoint/index coverage; reserved mode prefixes excluded.')
(here/'golden.json').write_text(json.dumps(report,indent=2)+'\n')
print('BC6H golden: %d blocks x signed/unsigned x 16 texels; O1/O2 identical' % len(blocks))
