#!/usr/bin/env python3
"""Generate BC7 byte references using the pinned, independent bc7decomp source.

The GPU decoder is adapted from bcdec; this oracle is not linked at runtime.
All 512 blocks are valid. Random endpoint/index payloads are deterministic;
mode, partition, rotation, index selection and P bits are covered explicitly.
"""
import ctypes
import hashlib
import json
from pathlib import Path
import struct
import subprocess
import tempfile

here = Path(__file__).resolve().parent
metadata = json.loads((here / 'source.json').read_text())
for name, expected in metadata['files'].items():
    if hashlib.sha256((here / name).read_bytes()).hexdigest() != expected:
        raise ValueError('BC7 reference source mismatch: ' + name)
# BC7 mode descriptors: subsets, partition bits, rotation bits, selection bits,
# RGB bits, alpha bits, endpoint P bits, shared P bits.
modes = [(3,4,0,0,4,0,1,0), (2,6,0,0,6,0,0,1), (3,6,0,0,5,0,0,0), (2,6,0,0,7,0,1,0),
         (1,0,2,1,5,6,0,0), (1,0,2,0,7,8,0,0), (1,0,0,0,7,7,1,0), (2,6,0,0,5,5,1,0)]
seed = 0x91B7C043
blocks = []
coverage = {i: {'blocks': 0, 'partitions': set(), 'rotation_selection': set(), 'pbits': set()} for i in range(8)}
def put(value, offset, bits, field):
    mask = (1 << bits) - 1
    return (value & ~(mask << offset)) | ((field & mask) << offset)
for configuration in range(64):
    for mode, (subsets, pb, rb, sb, cb, ab, ep, sp) in enumerate(modes):
        value = 0
        for word in range(4):
            seed ^= (seed << 13) & 0xffffffff
            seed ^= seed >> 17
            seed ^= (seed << 5) & 0xffffffff
            value |= seed << (32 * word)
        value = put(value, 0, mode + 1, 1 << mode)
        offset = mode + 1
        value = put(value, offset, pb, configuration); offset += pb
        rotation = configuration & 3 if rb else 0
        selection = (configuration >> 2) & 1 if sb else 0
        value = put(value, offset, rb, rotation); offset += rb
        value = put(value, offset, sb, selection); offset += sb
        offset += 2 * subsets * (3 * cb + ab)
        pbits = 2 * subsets if ep else subsets if sp else 0
        value = put(value, offset, pbits, configuration)
        block = value.to_bytes(16, 'little')
        blocks.append(block)
        c = coverage[mode]
        c['blocks'] += 1
        c['partitions'].add((value >> (mode + 1)) & ((1 << pb) - 1))
        c['rotation_selection'].add((rotation, selection))
        c['pbits'].add((value >> offset) & ((1 << pbits) - 1))
fill = struct.pack('<4I', *([0x40] * 4))  # GPU fill with a valid mode-6 block.
with tempfile.TemporaryDirectory(prefix='hybris-bc7-golden-') as temporary:
    temp = Path(temporary)
    wrapper = temp / 'reference.cpp'
    wrapper.write_text('#include "bc7decomp.h"\nextern "C" int decode(const void *src, void *dst) {\n'
                       'return bc7decomp::unpack_bc7(src, static_cast<bc7decomp::color_rgba *>(dst));\n}\n')
    outputs = []
    for variant, flags in [('default', []), ('scalar', ['-U__SSE2__'])]:
        library = temp / (variant + '.so')
        subprocess.run(['g++', '-std=c++11', '-O2', '-shared', '-fPIC', *flags, '-I', str(here),
                        str(wrapper), str(here / 'bc7decomp.cpp'), '-o', str(library)], check=True)
        decoder = ctypes.CDLL(str(library)).decode
        decoder.argtypes = [ctypes.c_void_p, ctypes.c_void_p]
        decoder.restype = ctypes.c_int
        decoded = []
        for block in [*blocks, fill]:
            source = ctypes.create_string_buffer(block)
            target = ctypes.create_string_buffer(64)
            if decoder(source, target) != 1:
                raise ValueError('reference rejected a generated BC7 block')
            decoded.append(target.raw)
        outputs.append(decoded)
    if outputs[0] != outputs[1]:
        raise ValueError('default/scalar BC7 reference disagreement')
decoded = outputs[0]
rows = []
for block, pixels in zip(blocks, decoded):
    words = struct.unpack('<4I', block)
    colors = struct.unpack('<16I', pixels)
    rows.append('    {{' + ', '.join('0x%08xu' % w for w in words) + '},\n'
                '     {' + ', '.join('0x%08xu' % w for w in colors) + '}}')
result = '// Generated by reference/bc7/generate.py using pinned bc7decomp.\n'
result += '#define BC7_VECTOR_COUNT 512u\n'
result += 'static const struct { uint32_t block[4], rgba[16]; } bc7_vectors[BC7_VECTOR_COUNT] = {\n'
result += ',\n'.join(rows) + '\n};\n'
result += 'static const uint32_t bc7_fill_rgba[16] = {' + ', '.join('0x%08xu' % w for w in struct.unpack('<16I', decoded[-1])) + '};\n'
(here.parent.parent / 'bc7_fixture.inc').write_text(result)
summary = {'reference': metadata, 'generator_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
           'compiler': subprocess.check_output(['g++', '--version'], text=True).splitlines()[0],
           'blocks': len(blocks), 'decoded_texels': len(blocks) * 16,
           'default_scalar_agreement': True, 'gpu_fill_word': '0x00000040',
           'block_bytes_sha256': hashlib.sha256(b''.join(blocks)).hexdigest(),
           'rgba_bytes_sha256': hashlib.sha256(b''.join(decoded[:-1])).hexdigest(),
           'fixture_sha256': hashlib.sha256(result.encode()).hexdigest(),
           'coverage': {mode: {key: sorted(value) if isinstance(value, set) else value for key, value in record.items()}
                        for mode, record in coverage.items()}}
(here / 'golden.json').write_text(json.dumps(summary, indent=2) + '\n')
print('BC7 golden:', summary['blocks'], 'valid blocks,', summary['decoded_texels'], 'texels; default/scalar agree')
