#!/usr/bin/env python3
"""Compile and validate the Vulkan 1.0 BC decoder; no build-time compiler needed."""
from pathlib import Path
import struct
import subprocess
import tempfile

here = Path(__file__).resolve().parent
with tempfile.TemporaryDirectory(prefix='hybris-bc-') as temporary:
    target = Path(temporary) / 'bc.spv'
    subprocess.run(['glslangValidator', '-V', '--target-env', 'vulkan1.0',
                    str(here / 'bc_decode.comp'), '-o', str(target)], check=True)
    subprocess.run(['spirv-val', '--target-env', 'vulkan1.0', str(target)], check=True)
    binary = target.read_bytes()
    words = struct.unpack('<' + 'I' * (len(binary) // 4), binary)
    rows = ''.join('    ' + ', '.join(f'0x{w:08x}' for w in words[i:i+8]) + ',\n'
                   for i in range(0, len(words), 8))
    (here / 'bc_decode.inc').write_text('// Generated by generate-bc.py.\n'
        'static const uint32_t hybris_bc_decode_spv[] = {\n' + rows + '};\n')
