#!/usr/bin/env python3
"""Generate shallow-copy sizes for VkDeviceCreateInfo input chain nodes."""
import argparse
import hashlib
from pathlib import Path
import xml.etree.ElementTree as ET


def generate(registry):
    data = registry.read_bytes()
    root = ET.fromstring(data)
    enum_guards = {entry.get('name'): entry.get('protect')
                   for entry in root.iter('enum') if entry.get('protect')}
    providers = {}
    for owner in [*root.findall('feature'), *root.findall('./extensions/extension')]:
        if 'vulkan' not in owner.get('api', owner.get('supported', '')).split(','):
            continue
        for require in owner.findall('require'):
            if require.get('api') not in (None, 'vulkan'):
                continue
            for entry in require.findall('type'):
                providers.setdefault(entry.get('name'), set()).add(owner.get('name'))
    groups = {}
    for node in root.findall('./types/type'):
        if 'VkDeviceCreateInfo' not in node.get('structextends', '').split(',') or node.get('alias'):
            continue
        name = node.get('name')
        guards = providers.get(name)
        if not guards:
            continue
        stype = node.find("member[name='sType']")
        if stype is None or not stype.get('values'):
            raise ValueError(f'missing sType: {name}')
        guard = ' || '.join(f'defined({value})' for value in sorted(guards))
        protect = enum_guards.get(stype.get('values'))
        if protect:
            guard = f'({guard}) && defined({protect})'
        groups.setdefault(guard, []).append((stype.get('values'), name))
    lines = ['/* SPDX-License-Identifier: Apache-2.0',
             ' * Generated by tools/generate-device-create-sizes.py.',
             f' * vk.xml SHA256: {hashlib.sha256(data).hexdigest()}', ' */']
    for guard, entries in sorted(groups.items()):
        lines.append(f'#if {guard}')
        for stype, name in sorted(entries):
            lines.append(f'case {stype}: return sizeof({name});')
        lines.append('#endif')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('registry', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    args.output.write_text(generate(args.registry))
